# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # step 1 install  pipenv
      - run:
          name: install  pipenv and activate
          command: |
            pip install  pipenv
            pipenv shell
      # Step 2: obtain repo from GitHub
      - checkout
      # Step 3: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pipenv install  --dev
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            make test 