# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      # step 1 install  pipenv
      - run:
          name: install  pipenv and activate
          command: |
            sudo pip install pipenv
      # Step 2: obtain repo from GitHub
      - checkout
      # Step 3: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pipenv install --dev
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv run "python -m pytest --cov"